apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml  # Monter le fichier à l'emplacement exact
              subPath: prometheus.yml  # Utilisation de subPath pour le fichier spécifique
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config  # Assurez-vous que le ConfigMap est correctement référencé
