apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Fréquence de récupération des métriques

    scrape_configs:
  - job_name: 'nodejs'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 20s  # Augmente le timeout si nécessaire
    retries: 3  # Nombre de tentatives avant d'échouer
    static_configs:
      - targets: ['backend-service.default.svc.cluster.local:3000']

  - job_name: 'redis'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 20s  # Augmente le timeout pour Redis
    retries: 3
    static_configs:
      - targets: ['redis-master-service.default.svc.cluster.local:6379']

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter.default.svc.cluster.local:9121']  # Vérifiez que l'exporter Redis est bien déployé et accessible
