apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'nodejs'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['backend-service.default.svc.cluster.local:3000']

      - job_name: 'redis'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['redis-master-service.default.svc.cluster.local:6379']

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter.default.svc.cluster.local:9121']
