apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: ClusterIP # Ou ClusterIP si tu veux juste l’utiliser en interne
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
