apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: arthurescriou/node-redis:1.0.6
          ports:
            - containerPort: 7000
          resources:
            limits:
              cpu: "1"
              memory: "128Mi"
            requests:
              cpu: "128m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "7000"
            - name: REDIS_URL
              value: "redis://redis-master:6379"
            - name: REDIS_REPLICAS_URL
              value: "redis://redis-replicas:6379"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
