apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 3000    # Le port où ton service backend est accessible
      targetPort: 3000  # Le port sur lequel ton backend écoute
  selector:
    app: backend    # Le label correspondant à ton déploiement
