apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # Port exposé à l'extérieur du cluster
      targetPort: 3000  # Port du container Node.js
  type: LoadBalancer  # Ou ClusterIP si tu veux un service interne seulement
