apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replicas-deployment
spec:
  replicas: 2  # Le nombre initial de réplicas
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
