apiVersion: v1
kind: Service
metadata:
  name: redis-react
spec:
  selector:
    app: redis-react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Expose l'application à l'extérieur du cluster
