global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nodejs"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["redis-node:3000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
